FROM node:latest as builder

COPY package.json package-lock.json ./

RUN npm i && mkdir /web && mv ./node_modules ./web

WORKDIR /web

COPY . . 

ARG ECO_SERVER_HOST
ARG ECO_SERVER_PORT
ARG ECO_VK_ID
ARG ECO_CLIENT_PORT
ARG ECO_JWT_SECRET

ENV ECO_SERVER_HOST ${ECO_SERVER_HOST}
ENV ECO_SERVER_PORT ${ECO_SERVER_PORT}
ENV ECO_VK_ID ${ECO_VK_ID}
ENV ECO_CLIENT_PORT ${ECO_CLIENT_PORT}
ENV ECO_JWT_SECRET ${ECO_JWT_SECRET}


RUN npm run build

FROM nginx:latest

COPY ./.nginx/nginx.template.conf /etc/nginx/nginx.template.conf
COPY ./.nginx/run_nginx.sh /

RUN chmod +x /run_nginx.sh


RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /web/dist /usr/share/nginx/html

WORKDIR /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT [ "/run_nginx.sh" ]

