FROM node:latest as builder

COPY package.json package-lock.json ./

RUN npm i && mkdir /web && mv ./node_modules ./web

WORKDIR /web

COPY . . 

RUN touch .env 

RUN echo "ECO_SERVER_HOST: $${ECO_SERVER_HOST}" >> .env
RUN echo "ECO_SERVER_PORT: $${ECO_SERVER_PORT}" >> .env
RUN echo "ECO_VK_ID: $${ECO_VK_ID}" >> .env
RUN echo "ECO_CLIENT_PORT: $${ECO_CLIENT_PORT}" >> .env
RUN echo "ECO_JWT_SECRET: $${ECO_JWT_SECRET}"  >> .env

RUN npm run build

FROM nginx:latest

COPY ./.nginx/nginx.template.conf /etc/nginx/nginx.template.conf
COPY ./.nginx/run_nginx.sh /

RUN chmod +x /run_nginx.sh


RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /web/dist /usr/share/nginx/html


EXPOSE 80

ENTRYPOINT [ "/run_nginx.sh" ]

