export const REGISTRATION__STARTED = "REGISTRATION__STARTED";
export const REGISTRATION__REJECTED = "REGISTRATION__REJECTED";

export const LOGIN__STARTED = "LOGIN__STARTED";
export const LOGIN__REJECTED = "LOGIN__REJECTED";

export const VK_AUTH__STARTED = "VK_AUTH__STARTED";
export const VK_AUTH__REJECTED = "VK_AUTH__REJECTED";

export const GOOGLE_AUTH__STARTED = "GOOGLE_AUTH__STARTED";
export const GOOGLE_AUTH__REJECTED = "GOOGLE_AUTH__REJECTED";

export const CHECK_AUTHORIZATION = "CHECK_AUTHORIZATION";

export const LOGOUT = "LOGOUT";

export const AUTHORIZATION__COMPLETE = "AUTHORIZATION__COMPLETE";

export const AUTH_MODAL_OPEN = "AUTH_MODAL_OPEN";
export const AUTH_MODAL_CLOSE = "AUTH_MODAL_CLOSE";
