export const GET_USER = "GET_USER";
export const GET_USER_COMPLETED = "GET_USER_COMPLETED";
export const GET_USER_REJECTED = "GET_USER_REJECTED";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_COMPLETED = "UPDATE_USER_COMPLETED";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";

export const DELETE_USER = "DELETE_USER";
