export const CREATE_CATALOG = "CREATE_CATALOG";
export const CREATE_CATALOG_SUCCESS = "CREATE_CATALOG_SUCCESS";
export const CREATE_CATALOG_REJECT = "CREATE_CATALOG_REJECT";

export const GET_CATALOGS = "GET_CATALOGS";
export const GET_CATALOGS_SUCCESS = "GET_CATALOGS_SUCCESS";
export const GET_CATALOGS_REJECT = "GET_CATALOGS_REJECT";

export const UPDATE_CATALOG = "UPDATE_CATALOG";
export const UPDATE_CATALOG_SUCCESS = "UPDATE_CATALOG_SUCCESS";
export const UPDATE_CATALOG_REJECT = "UPDATE_CATALOG_REJECT";

export const UPDATE_CATALOG_PRODUCTS = "UPDATE_CATALOG_PRODUCTS";
export const UPDATE_CATALOG_PRODUCTS_SUCCESS =
  "UPDATE_CATALOG_PRODUCTS_SUCCESS";
