export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_REJECT = "CREATE_PRODUCT_REJECT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_REJECT = "UPDATE_PRODUCT_REJECT";

export const UPDATE_FAVORITE_PRODUCT = "UPDATE_FAVORITE_PRODUCT";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_REJECT = "GET_PRODUCTS_REJECT";
