export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
export const UPDATE_FAVORITE_SUCCESS = "UPDATE_FAVORITE_SUCCESS";
export const UPDATE_FAVORITE_REJECT = "UPDATE_FAVORITE_REJECT";

export const GET_FAVORITE = "GET_FAVORITE";
export const GET_FAVORITE_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_REJECT = "GET_FAVORITE_REJECT";
