export const UPDATE_BASKET = "UPDATE_BASKET";
export const UPDATE_BASKET_SUCCESS = "UPDATE_BASKET_SUCCESS";
export const UPDATE_BASKET_REJECT = "UPDATE_BASKET_REJECT";

export const GET_BASKET = "GET_BASKET";
export const GET_BASKET_SUCCESS = "GET_BASKET_SUCCESS";
export const GET_BASKET_REJECT = "GET_BASKET_REJECT";

export const OPEN_BASKET = "OPEN_BASKET";
export const CLOSE_BASKET = "CLOSE_BASKET";
