export const OPEN_CREATE_ORDER_MODAL = "OPEN_CREATE_ORDER_MODAL";
export const CLOSE_CREATE_ORDER_MODAL = "CLOSE_CREATE_ORDER_MODAL";

export const SET_CURRENT_ORDER = "SET_CURRENT_ORDER";
export const DELETE_CURRENT_ORDER = "DELETE_CURRENT_ORDER";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_REJECT = "GET_ORDERS_REJECT";

export const CHECKOUT_ORDER = "CHECKOUT_ORDER";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_REJECT = "CREATE_ORDER_REJECT";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_REJECT = "UPDATE_ORDER_REJECT";
